### PR TITLE
Make parts of doTiledShepherdSegmentation() separate

### PR DESCRIPTION
**Pull request by gillins**
....so they can potentially be called in parallel.

As promised @neilflood here is a very rough PR. Let me know what you think before I tidy up.

The idea is that a users script would run `doTiledShepherdSegmentation_prepare()` before submitting a script to call `doTiledShepherdSegmentation_doOne()` for each tile into a batch queue or whatever. The actual mechanism for passing `tileInfo` and the other parameters to each script is left to the user. When all these jobs have finished another script should be run to call `doTiledShepherdSegmentation_finalize()`. 

This is quite a minor change compared to what could be done but my idea was to leave it to others to flesh out something for their particular use case and batch queuing system.

### CODE REVIEW

**Comment by neilflood** [comment]
OK, I think I get the idea. So, for a given parallel environment (e.g. AWS Batch), a user would be writing their own version of doTiledShepherdSegmentation(), and probably a separate main script which would call doTiledShepherdSegmentation_doOne() for a single tile. Have I understood?

**Comment by neilflood** [comment]
I assume you are planning to add an implementation for AWS Batch (or something). Do you think we should put that in a separate file (e.g. tiling_awsbatch.py), so that if we ever add other implementations, they would each have their own file? It would also make a good example for others, so if anyone contributed an implementation, they would also do it in a separate file. Dunno, but I  think that the current tiling.py (at 1870 lines) is already quite long enough.

**Comment by gillins** [comment]
Yes that's right. They will probably need 3 different main scripts for the different stages. 

Yes I guess I should add an AWS Batch implementation (maybe in a subdir). Things get a bit specific here with S3 bucket names, queue names etc, but I could provide something where these are passed in. One thing that I'll have to be careful is with maintaining the `tileFilenames` dictionary - the "doOne" script will be operating on a local file somewhere, then copy this to S3. So when the "finalize" script runs it will need to see filenames starting with `/vsis3` etc...

Are you happy enough with this approach for me to push on?

**Comment by neilflood** [comment]
Yes, happy for you to continue. I don't mind whether you do your AWS implementation in there or not, I was just figuring that you would be doing one anyway, one way or another. Up to you. I am guessing that as you put it together, the changes you are making here will evolve, as other problems crop up, but up to you how you manage that. 

Good on you for finding the strength :-)

**Comment by petescarth** [comment]
Hi @gillins this all sounds good to me. From memory, this prepare-parallel_segment-assemble workflow is similar to the way the rsgislib version was hacked to run in parallel but I could never quite understand the hacking process to reproduce ;) Agree it would be spectacular to be able to run this on AWS batch for specific workflows.

**Review by neilflood — APPROVED** [review]
I am happy for this to merge. Most of the AWS example code is outside my expertise, but the changes to the core code are fine. I also ran it through my new test script (which I will add shortly), and it was fine.

**Pull request merged**
