### PR TITLE
Testing Sphinx with numpydoc

### PR DESCRIPTION
**Pull request by neilflood**
Switch on numpydoc Sphinx extension, and have a go at re-formatting the shepseg module, to see how it might look. This is very much just to test and see. Initially only modified the shepseg module. It took a couple of hours, I think, but not too bad. 

Ping @gillins 
No rush. When you get a moment, have a look at the rendered RTD page, and at the original code, and see what you think. 

I think it is do-able, if we want to. It certainly does lots of nice formatting without the really dense docstrings that raw Sphinx requires, but it does still require some discipline. I have left some of the docstrings raw, because some are nice and short as they are, without needing much formatting. Or we could get really rigid and make everything conform to the same pattern. I dunno.....

I used the References facility in the main module docstring, which seems nice, but also perhaps overly complicated. 

The See Also section automatically makes links out of things, which is cool, but also more complicated. 

No urgency at all, just playing because I can. :-)

### CODE REVIEW

**Comment by neilflood** [comment]
@gillins 
In a couple of functions in tilingstats.py, you have segSize as a numba.typed.Dict. I think that's not right, I think it is always an array of shape (numSegments+1, )

**Comment by gillins** [comment]
Yes - you are right. I'll update.

**Comment by neilflood** [comment]
One other thing. I have been using SegIdType for the type of things which are segment ID numbers, since that is the type I defined for it. I think it is worth saying this explicitly, rather than just `int`, to emphasize what is going on.

**Comment by neilflood** [comment]
I did wonder about removing that checkSegCompleteSpatial function :-)

On the topic of faking @jitclass. I have something which works, although my attempts to make it as neat as possible have run into weirdness at several levels. It is usable, though. So, do you think I should put it into this PR now? That way, you can see what I am doing, and the final rendered doc will at least be complete.

**Comment by gillins** [comment]
Happy to do whatever you this is best with @jitclass. Yep if you think it makes sense to go in here, that's fine with me.

**Comment by neilflood** [comment]
OK. I will do a final check, and then merge this PR, as is. 

After that, I will start a new one for the jitclass thing.

**Pull request merged**
