### PR TITLE
Sphinx tidy

### PR DESCRIPTION
**Pull request by neilflood**
This PR is just draft. I am accumulating small changes which all seem to help, especially with some of the things which are different in recent Sphinx versions. We can add to this together, I guess, until we think it is ready. Dunno......

### CODE REVIEW

**Comment by neilflood** [comment]
Now that I have the sidebar table of contents working OK again, I am leaning towards not having many explicit `func` links in the docstring text, especially for functions within the same module. It makes them hard to read when coding, and the functions are fairly easy to find in the TOC. What do you think?

**Comment by gillins** [comment]
Thanks for looking into this @neilflood, I kind of like the hyperlinks and find them handy in the python.org documentation to be able to go straight to something. I was assuming most people would be using readthedocs rather than the docstrings directly? But happy to go with whatever is easiest really - if you have strong thoughts about not having them that's fine.
How you you feel about having a sphinx run as part of the CI workflow? Would be good to know that a given PR won't break the documentation beforehand...
Thanks for fighting with this, hope to help out next week straightening it all up.

**Comment by neilflood** [comment]
re: hyperlinks. I have mixed feelings. It does help a bit when reading on readthedocs (i.e. as a user), but when reading the code itself (i.e. as a programmer working on the code) I find it very disruptive. I think I would prefer to include them only when it seems important. Same goes for backtics (especially double backtics). 

re: sphinx in CI. Yes, a good thought. If we can work out how to make it report something sensible. I guess it depends what sort of breakages end up being detectable. 

No worries, happy to be helping. It is rather a battle, though!

Currently trying to track down some of those jitclass-related problems. Nightmare. (e.g. for some reason, that new SegPoint class now refuses to be indexed, and is just missing from the doc page. Not serious in itself, but annoying)

**Comment by neilflood** [comment]
Just a little note on the commits about the mock list. I have added some code to conf.py which will only add things to the list to be mock-ed if they are not present. So, in our normal desktop test environment, which has the real scipy/sklearn/numba etc., they will not be mock-ed. 

This changes several things. 

1. The voluminous Sphinx warning messages about the various mock-ed objects disappear. This is good, even if they were (mostly) harmless, as they made it difficult to see any other errors we might need to know about
2. The Sphinx run goes _much_ faster (no, I don't know why). Running Sphinx while testing things is very slow, and this is a great improvement. 
3. All the jitclass classes now disappear from the resulting documentation pages. This is bad. Before this, I was finding that some jitclass classes were absent from the output, but not all of them. I don't know how this will look on ReadTheDocs, as the environment there is different. Sigh.....

I just wanted to note all that down, so it is recorded somewhere.

**Comment by gillins** [comment]
I think there is the ability to [specify extra Python packages you want in readthedocs](https://docs.readthedocs.io/en/stable/faq.html#my-documentation-requires-additional-dependencies) so maybe we don't mock at all?
Maybe if `'sphinx' in sys.modules` we define `@jitclass` to do nothing to workaround this?
I just checked and the Numba guys use Sphinx so there must be a way to get this all working....

**Comment by neilflood** [comment]
That's good to know, at least. 

I think let's see how this looks once it gets to ReadTheDocs, then consider if we need to do anything more drastic. I am still unsure whether the jitclass-ed classes are going to be included or not. 

Next week, we can have a more serious discussion about the use of links in docstrings. I did have a giggle at another section in that RTD FAQ you just sent, a few paragraphs down, about [legible docstrings](https://docs.readthedocs.io/en/stable/faq.html#does-read-the-docs-work-well-with-legible-docstrings). 

I am happy to keep going on this, though, to try to get it right. I think I would also like to have some more goes at the numpydoc extension........

**Pull request merged**
