### PR TITLE
Add ability to calculate spatial stats on segments

### PR DESCRIPTION
**Pull request by gillins**
Also took the opportunity to create a new `tilingstats` module to handle both the non-spatial and spatial tiling stats....

New test program `pyshepseg_variograms.py` to calculate variograms using the new functionality.

ping: @petescarth

### CODE REVIEW

**Comment by neilflood** [comment]
After pondering lots of bits of this, the main thing I would suggest might change would be that perhaps you don't need to use convertPtsInto2DArray before passing to userFunc. You can certainly calculate the variogram directly from the List of points you have already, and I think that would mostly be true of other spatial calculations. If there were something which needed it to be in 2D form, that could be done within the userFunc, but in general I think it would be more flexible if just the list were passed in. 

I did have various ideas about other things which could be done differently, but all of them ran into hurdles in the details, which meant they were not actually any better than what you have. I still kind of wish it were possible to leverage the existing makeSegmentLocation function to do the accumulation of spatial information, but it creates too many problems in this context, so I think what you have is best. 

Similarly, it kind of grates that we can't use the existing logic for the main tile loop and rat paging, etc., instead of reproducing it,  but I can see why that comes out too complicated. Sigh.......

**Comment by gillins** [comment]
I didn't actually intend to have convertPtsInto2DArray when I started this, but when doing the variogram stuff I realised that would be very slow as I'd have to search all the data potentially to find the neighbouring pixel. I then started working out how to build a spatial index to speed this up, then realised a 2D array is a spatial index where I can find neighbouring pixels very quickly....
Do you think this would be better as an optional step (ie have the userFunc call convertPtsInto2DArray if it wants to)? I was kind of thinking that needing to search neighbouring pixels would be a common thing, but maybe not.

Yes agree re: existing logic. Sigh indeed.

BTW I can't build sphinx from this PR anymore, so I'll need to fix that up at least before merging.

**Comment by neilflood** [comment]
My thinking was that you don't need to find neighbouring pixels, just do every pair, and bin the distances as integers, as you have done. Anything with a distance greater than maxDist is discarded. Something like this

```
nPts = len(pts)
maxDistSqrd = maxDist**2
for i in range(nPts-1):
    for j in range(i+1, nPts):
        if pts[j].val != imgNullVal and pts[i].val != imgNullVal:
            xd = pts[j].x - pts[i].x
            yd = pts[j].y - pts[i].y
            distSqrd = xd*xd + yd*yd
            if distSqrd <= maxDistSqrd:
                dist = int(round(numpy.sqrt(distSqrd)))
                if dist <= maxDist:
                    counts[dist-1] += 1
                    sumDifSqs[dist-1] += (pts[j].val - pts[i].val) ** 2
```
The slowest part is the sqrt, and that is only done if it will (almost) definitely be within maxDist, as the distSqrd is checked first. 

All the pixels which are outside the segment are not present at all, so don't need to be skipped, thus we are only ever dealing with pairs which are a part of the segment (although could still be null). The simpler distance check does the same job as the moving window in your code. One could do an even simpler version of that, by first checking the xd and yd separately, because for dist to be <= maxDist, at least one of xd or yd would have to be <= maxDist. However, I am not sure it would matter much. I guess it depends on the segment size/shape. 

Does that make sense? Do you think this will come out to be greatly slower than the 2D moving window version? I am unsure, now that I have written it out. There is a trade-off with constructing the 2D array, too, so I dunno.

**Comment by neilflood** [comment]
I have just been trying to think through which comes out slower. It depends so heavily on the "typical" shapes of the segments that I am quite unsure. Lots of narrow and/or odd shaped segments will be faster in my version, but lots of rounder/rectangular segments will be faster your way. I dunno......

**Comment by neilflood** [comment]
OK, I have done a back-of-envelope check of "typical" figures. I used a Landsat-8 image I had handy (p091r081_20220213), and did a segmentation on the three visible bands. I then did a count of the number of pixel pairs to be considered for the per-segment variograms, using either the current 2D array approach, or my suggestion above. 

Rough order of magnitude shows about 3 times as many pixel pairs to consider using my suggested approach. 

While this is not a full timing test, as it does not include exactly what must be done for each pair, it does strongly suggest that your current approach is likely to be faster, or at least no slower.

So, I withdraw my silly suggestion, and support keeping what you have proposed. 
:-)

**Comment by gillins** [comment]
I was curious and just had a go at this. See the `notile` branch in my fork. With the small subset I was working with it tool 2m12secs, but with the existing method it only took 5secs... 
So I'll stick with what I've got but I have softened my stance a bit about building the tile first. There will be some stats (like working out the mean easting/northing) where the tile is totally unnecessary. How do you feel about the `userFunc` being passed the list of points and having to call `convertPtsInto2DArray` if it wants a tile instead?
Also, I'm thinking of allowing an optional final argument to `userFunc` so one can pass a `transform` or whatever extra info it needs to do the work...

**Comment by neilflood** [comment]
I think that sounds like a good plan. I agree, it will depend on exactly what statistic is being calculated, so having access to the raw points would give maximum flexibility, and a routine to convert that to a 2D array form will allow that approach when that is best. Very good. 

I do think some sort of optional argument would be good, but won't it run up against numba's typing rules? Will it still be able to jit, when it won't know the type of the argument?

**Comment by gillins** [comment]
I think the argument will need to be something that Numba knows how to deal with, ie an array, scalar or jitclass. It won't be able to be an arbitrary Python object like with RIOS. I'll have a go and see how it goes.

**Comment by neilflood** [comment]
So, will that mean you could get rid of the different variogram functions for different maxDist values? That would be good.

**Comment by gillins** [comment]
Yes I think it would.

**Comment by neilflood** [comment]
Very good. What assumptions are being made about userParam? Can it be either an array or a scalar? Always float? 

On the missingStatsValue thing - given that the result array(s) are created outside userFunc, would it make sense to fill them with the missingStatsValue before calling userFunc, and have the userFunc only fill in those elements which are not missing. Then the user does not have to think further about it.

**Comment by gillins** [comment]
I've tried having `userParam` a scalar (presumeably any type), an array and an jitclass and they all work...

I create the result arrays outsite of the loop to save time - do you think I should reset the values to `missingStatsValue` each time before I call `userFunc`?

**Comment by neilflood** [comment]
Good question. Ummm... yes, I think so. Just immediately before calling userFunc. I think it should be quite small compared to the computation going on inside userFunc. 

I dunno, I guess it doesn't make much difference. It should either be that, or it should be passed in to userFunc, explicitly and always. I saw your TODO not about it, and so it got me thinking.

**Comment by gillins** [comment]
Ah I forgot about the TODO. Good idea

**Comment by gillins** [comment]
Is this good to merge @neilflood ?

**Comment by neilflood** [comment]
I think so. Especially now that you have fixed the typo in the title :-)

Merge when you are happy, this is your baby.

**Pull request merged**
