### PR TITLE
add instructions for installing from conda-forge

### PR DESCRIPTION
**Pull request by gillins**
Now that it is available from conda-forge.

### CODE REVIEW

**Comment by neilflood** [comment]
Very good, I was thinking the same thing this morning. 

Looks like it needs a blank line after the double-colon (and people complain about LaTeX being picky..... :-)

**Comment by gillins** [comment]
Thanks @neilflood. Is the wording ok?

**Comment by neilflood** [comment]
Yes, I think that looks fine. Did you mean to make the package name in italics? I was expecting more like with double-back-tics (I am pretending I care much either way....)

**Comment by gillins** [comment]
Arghhh! Yes I meant double back tics...

**Comment by gillins** [comment]
Arghhh! Yes I meant double back tics...

**Comment by neilflood** [comment]
:-)
Looks like there is one more, on the last line of the Dependencies section.

**Pull request merged**
